// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: voucher_batches.sql

package queries

import (
	"context"
	"database/sql"
)

const createVoucherBatch = `-- name: CreateVoucherBatch :one
INSERT INTO voucher_batches (uuid, amount, metadata, provider_pkg)
VALUES (?1, ?2, ?3, ?4)
RETURNING id, uuid, provider_pkg, amount, metadata, created_at, updated_at
`

type CreateVoucherBatchParams struct {
	Uuid        string
	Amount      sql.NullFloat64
	Metadata    sql.NullString
	ProviderPkg string
}

func (q *Queries) CreateVoucherBatch(ctx context.Context, arg CreateVoucherBatchParams) (VoucherBatch, error) {
	row := q.db.QueryRowContext(ctx, createVoucherBatch,
		arg.Uuid,
		arg.Amount,
		arg.Metadata,
		arg.ProviderPkg,
	)
	var i VoucherBatch
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.ProviderPkg,
		&i.Amount,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteVoucherBatchByUUID = `-- name: DeleteVoucherBatchByUUID :exec
DELETE FROM voucher_batches
WHERE uuid = ?1
`

func (q *Queries) DeleteVoucherBatchByUUID(ctx context.Context, uuid string) error {
	_, err := q.db.ExecContext(ctx, deleteVoucherBatchByUUID, uuid)
	return err
}

const findVoucherBatchByCode = `-- name: FindVoucherBatchByCode :one
SELECT vb.id, vb.uuid, vb.provider_pkg, vb.amount, vb.metadata, vb.created_at, vb.updated_at
FROM voucher_batches vb
JOIN vouchers v ON v.batch_uuid = vb.uuid
WHERE v.code = ?1
LIMIT 1
`

func (q *Queries) FindVoucherBatchByCode(ctx context.Context, code string) (VoucherBatch, error) {
	row := q.db.QueryRowContext(ctx, findVoucherBatchByCode, code)
	var i VoucherBatch
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.ProviderPkg,
		&i.Amount,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findVoucherBatchByUUID = `-- name: FindVoucherBatchByUUID :one
SELECT id, uuid, provider_pkg, amount, metadata, created_at, updated_at
FROM voucher_batches
WHERE uuid = ?1
LIMIT 1
`

func (q *Queries) FindVoucherBatchByUUID(ctx context.Context, uuid string) (VoucherBatch, error) {
	row := q.db.QueryRowContext(ctx, findVoucherBatchByUUID, uuid)
	var i VoucherBatch
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.ProviderPkg,
		&i.Amount,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllVoucherBatches = `-- name: GetAllVoucherBatches :many
SELECT id, uuid, provider_pkg, amount, metadata, created_at, updated_at
FROM voucher_batches
ORDER BY created_at DESC
LIMIT ?2 OFFSET ?1
`

type GetAllVoucherBatchesParams struct {
	RowOffset int64
	RowLimit  int64
}

func (q *Queries) GetAllVoucherBatches(ctx context.Context, arg GetAllVoucherBatchesParams) ([]VoucherBatch, error) {
	rows, err := q.db.QueryContext(ctx, getAllVoucherBatches, arg.RowOffset, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VoucherBatch
	for rows.Next() {
		var i VoucherBatch
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.ProviderPkg,
			&i.Amount,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllVoucherBatchesCount = `-- name: GetAllVoucherBatchesCount :one
SELECT COUNT(id)
FROM voucher_batches
`

func (q *Queries) GetAllVoucherBatchesCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getAllVoucherBatchesCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const updateVoucherBatch = `-- name: UpdateVoucherBatch :exec
UPDATE voucher_batches
SET amount = ?1,
    metadata = ?2,
    updated_at = CURRENT_TIMESTAMP
WHERE uuid = ?3
`

type UpdateVoucherBatchParams struct {
	Amount   sql.NullFloat64
	Metadata sql.NullString
	Uuid     string
}

func (q *Queries) UpdateVoucherBatch(ctx context.Context, arg UpdateVoucherBatchParams) error {
	_, err := q.db.ExecContext(ctx, updateVoucherBatch, arg.Amount, arg.Metadata, arg.Uuid)
	return err
}
