// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: wallet-trns.sql

package queries

import (
	"context"
	"time"
)

const createWalletTrns = `-- name: CreateWalletTrns :one
INSERT INTO wallet_transactions (
  wallet_id, amount, new_balance, description
) 
VALUES 
  (?1, ?2, ?3, ?4)
RETURNING id, uuid, wallet_id, amount, new_balance, description, created_at
`

type CreateWalletTrnsParams struct {
	WalletID    int64
	Amount      float64
	NewBalance  float64
	Description string
}

func (q *Queries) CreateWalletTrns(ctx context.Context, arg CreateWalletTrnsParams) (WalletTransaction, error) {
	row := q.db.QueryRowContext(ctx, createWalletTrns,
		arg.WalletID,
		arg.Amount,
		arg.NewBalance,
		arg.Description,
	)
	var i WalletTransaction
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.WalletID,
		&i.Amount,
		&i.NewBalance,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const findWalletTrns = `-- name: FindWalletTrns :one
SELECT 
  id, 
  wallet_id, 
  amount, 
  new_balance, 
  description, 
  created_at 
FROM 
  wallet_transactions 
WHERE 
  id = ?1 
LIMIT 
  1
`

type FindWalletTrnsRow struct {
	ID          int64
	WalletID    int64
	Amount      float64
	NewBalance  float64
	Description string
	CreatedAt   time.Time
}

func (q *Queries) FindWalletTrns(ctx context.Context, id int64) (FindWalletTrnsRow, error) {
	row := q.db.QueryRowContext(ctx, findWalletTrns, id)
	var i FindWalletTrnsRow
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.Amount,
		&i.NewBalance,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const updateWalletTrns = `-- name: UpdateWalletTrns :exec
UPDATE
  wallet_transactions 
SET 
  wallet_id = ?1,
  amount = ?2,
  new_balance = ?3,
  description = ?4 
WHERE 
  id = ?5
`

type UpdateWalletTrnsParams struct {
	WalletID    int64
	Amount      float64
	NewBalance  float64
	Description string
	ID          int64
}

func (q *Queries) UpdateWalletTrns(ctx context.Context, arg UpdateWalletTrnsParams) error {
	_, err := q.db.ExecContext(ctx, updateWalletTrns,
		arg.WalletID,
		arg.Amount,
		arg.NewBalance,
		arg.Description,
		arg.ID,
	)
	return err
}
