CREATE TABLE IF NOT EXISTS devices (
    id INTEGER PRIMARY KEY,
    ip_address VARCHAR(15) NOT NULL DEFAULT '',
    mac_address CHAR(17) NOT NULL DEFAULT '',
    hostname VARCHAR(64) NOT NULL DEFAULT '',
    status INTEGER NOT NULL DEFAULT 2,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS index_mac_address ON devices(mac_address);
