CREATE TABLE IF NOT EXISTS notifications (
    id INTEGER PRIMARY KEY,
    subject VARCHAR(255) NOT NULL DEFAULT '',
    content TEXT NOT NULL DEFAULT '',
    status INTEGER  NOT NULL DEFAULT 0,
    type VARCHAR(100) NOT NULL DEFAULT 'info',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
