package migrate

import (
	"database/sql"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	sdkutils "github.com/flarewifi/sdk-utils"
)

type migDirection int

const (
	directionDown migDirection = iota
	directionUp
)

// listFiles enumerates the migration files (.up.sql or .down.sql, per d) under
// <pluginDir>/resources/migrations in apply order — ascending for up, descending
// for down. Dotfiles are skipped.
//
// It reads the directory directly rather than shelling out to a build-time helper
// (e.g. sqlc-gen.sh), so it behaves the same in dev and on a real router, where
// the build-time sqlc tooling is not available.
func listFiles(pluginDir string, d migDirection) ([]string, error) {
	migrationsDir := filepath.Join(pluginDir, "resources/migrations")

	list := []string{}
	if err := sdkutils.FsListFiles(migrationsDir, &list, false); err != nil {
		return nil, err
	}

	suffix := ".up.sql"
	if d == directionDown {
		suffix = ".down.sql"
	}

	files := []string{}
	for _, f := range list {
		if strings.HasSuffix(f, suffix) && !strings.HasPrefix(filepath.Base(f), ".") {
			files = append(files, f)
		}
	}

	if d == directionDown {
		sort.Sort(sort.Reverse(sort.StringSlice(files)))
	} else {
		sort.Strings(files)
	}
	return files, nil
}

// execFile runs every statement in a migration file within tx.
func execFile(path string, tx *sql.Tx) error {
	content, err := readMigration(path)
	if err != nil {
		return err
	}

	for _, q := range splitStatements(content) {
		q = strings.TrimSpace(q)
		if q == "" {
			continue
		}
		if _, err := tx.Exec(q); err != nil {
			return fmt.Errorf("error executing query from file %s: %w", path, err)
		}
	}
	return nil
}

// splitStatements splits SQL into statements on top-level ';', ignoring semicolons
// inside string literals ('...', "...") and comments (line -- and block /* */).
//
// A naive strings.Split(sql, ";") breaks whenever a ';' appears inside a comment
// (e.g. "status (0 = unread, 1 = read); read_at ..."), chopping the comment mid-way
// and leaving an invalid-SQL fragment that fails the whole migration transaction.
func splitStatements(sql string) []string {
	const (
		normal = iota
		inSingle
		inDouble
		inLine
		inBlock
	)

	var stmts []string
	var buf strings.Builder
	state := normal
	rs := []rune(sql)

	for i := 0; i < len(rs); i++ {
		c := rs[i]
		var next rune
		if i+1 < len(rs) {
			next = rs[i+1]
		}

		switch state {
		case inSingle:
			buf.WriteRune(c)
			if c == '\'' {
				state = normal
			}
		case inDouble:
			buf.WriteRune(c)
			if c == '"' {
				state = normal
			}
		case inLine:
			buf.WriteRune(c)
			if c == '\n' {
				state = normal
			}
		case inBlock:
			buf.WriteRune(c)
			if c == '*' && next == '/' {
				buf.WriteRune(next)
				i++
				state = normal
			}
		default: // normal
			switch {
			case c == '\'':
				state = inSingle
				buf.WriteRune(c)
			case c == '"':
				state = inDouble
				buf.WriteRune(c)
			case c == '-' && next == '-':
				state = inLine
				buf.WriteRune(c)
			case c == '/' && next == '*':
				state = inBlock
				buf.WriteRune(c)
			case c == ';':
				stmts = append(stmts, buf.String())
				buf.Reset()
			default:
				buf.WriteRune(c)
			}
		}
	}

	if strings.TrimSpace(buf.String()) != "" {
		stmts = append(stmts, buf.String())
	}
	return stmts
}

// readMigration reads a migration file, normalizing a legacy Postgres primary-key
// declaration to its SQLite equivalent. Postgres support was removed and every
// in-tree migration is authored for SQLite; this conversion only guards against
// older plugin migrations that still carry the Postgres syntax.
func readMigration(path string) (string, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return "", err
	}
	return strings.ReplaceAll(
		string(data),
		"INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY",
		"INTEGER PRIMARY KEY",
	), nil
}
