package migrate

import (
	"os"
	"strings"
)

// Fix migration files to be compatible with postgres and sqlite.
// It transforms the primary key definitions and auto-increment syntax suitable for each database.

func patchFile(file string, driver string) (content string, err error) {
	// SQLite primary key syntax:
	// id INTEGER PRIMARY KEY

	data, err := os.ReadFile(file)
	if err != nil {
		return content, err
	}

	// Always use SQLite syntax - convert any postgres syntax to sqlite
	content = strings.ReplaceAll(string(data), "INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY", "INTEGER PRIMARY KEY")

	return content, nil
}
