package migrate

import (
	"core/db"
	"os"
	"strings"
)

// Fix migration files to be compatible with postgres and sqlite.
// It transforms the primary key definitions and auto-increment syntax suitable for each database.

func patchFile(file string, driver string) (content string, err error) {
	// Postgres primary key syntax:
	// id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY

	// SQLite primary key syntax:
	// id INTEGER PRIMARY KEY

	data, err := os.ReadFile(file)
	if err != nil {
		return content, err
	}

	if driver == db.DriverPostgres {
		content = strings.ReplaceAll(string(data), "INTEGER PRIMARY KEY", "INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY")
	} else {
		// sqlite
		content = strings.ReplaceAll(string(data), "INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY", "INTEGER PRIMARY KEY")
	}

	return content, nil
}
