---

services:
  app:
    build:
      context: .
    volumes:
      - ./:/app
      - './openwrt-files/etc/config:/etc/config'
      - './core/build/devkit/extras/config/database.json:/app/config/database.json'
    ports:
      - 3000:3000
    environment:
      - GOCACHE=/app/.tmp/go/cache
      - GOMODCACHE=/app/.tmp/go/mod
    networks:
      flare_network:

  pg:
    image: postgres:17
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=flarehotspot_dev
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      flare_network:

  pgadmin:
    image: dpage/pgadmin4:9
    ports:
      - 3001:80
    depends_on:
      - pg
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
      - PGPASS_FILE=/pgpass
    volumes:
      - ./core/build/devkit/extras/pgadmin4/servers.json:/pgadmin4/servers.json
    networks:
      flare_network:

  docs:
    build:
      context: ./sdk/mkdocs
    volumes:
      - ./sdk/mkdocs:/docs
    ports:
      - 3002:8000

volumes:
  pgdata:

networks:
  flare_network:
    external: true
