---
site_name: Flarewifi Docs
site_url: https://docs.flarewifi.com
site_description: "Official developer documentation for the Flarewifi platform:
  plugin SDK, APIs, and guides."

theme:
  name: material
  palette:
    scheme: default
    primary: blue
    accent: light-blue
  features:
    - navigation.tracking
    - navigation.footer
    - search.highlight
    - search.suggestions
    - content.code.annotate
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - admonition
  - attr_list
  - def_list

nav:
  - Tutorials:
      - "Getting Started": guides/getting-started.md
      - "Creating a plugin": guides/creating-a-plugin.md
      - "Routes and Navigation": guides/routes-and-navigation.md
      - "Rendering Views": guides/rendering-views.md
      - "Form Submission": guides/form-submission.md
      - "Form Validator": guides/defining-form-validator.md
      - "Saving Data": guides/saving-data.md
      - "Storing Files": guides/storing-files.md
      - "Translations": guides/translations.md
      - "Core Database Tables": guides/core-database.md
      - "Database Migrations": guides/database-migrations.md
      - "Error Handling": guides/error-handling.md
      - "Handling Events": guides/handling-events.md
      - "Debugging": guides/debugging.md
      - "FAQ": guides/faq.md
  - Examples:
      - "Accept Payments": tutorials/accepting-payments.md
      - "Create Theme":
          - "Creating a Theme": tutorials/creating-a-theme/index.md
          - "Customizing the Admin Interface": tutorials/creating-a-theme/page2.md
  - API Reference:
      - "IPluginApi": api/plugin-api.md # Must always be on top
      - "Assets Manifest": api/assets-manifest.md
      - "IAccountsApi": api/accounts-api.md
      - "IAdsApi": api/ads-api.md
      - "IClientDevice": "api/client-device.md"
      - "IClientSession": "api/client-session.md"
      - "IConfigApi": api/config-api.md
      - "IEventsApi": api/events-api.md
      - "IFirewallAPI": api/firewall-api.md
      - "IHttpApi": api/http-api.md
      - "IHttpAuth": api/http-auth.md
      - "IHttpCookie": api/http-cookie.md
      - "IHttpFormsApi": api/http-forms-api.md
      - "IHttpHelpers": api/http-helpers.md
      - "IHttpNavsApi": api/http-navs-api.md
      - "IHttpResponse": api/http-response.md
      - "IHttpRouterApi": api/http-router-api.md
      - "IInAppPurchasesApi": api/inapp-purchases-api.md
      - "ILoggerApi": api/logger-api.md
      - "IMachineApi": api/machine-api.md
      - "INetworkApi": api/network-api.md
      - "INetworkDevice": api/network-device.md
      - "INetworkInterface": api/network-interface.md
      - "INotification": api/notification.md
      - "IPaymentsApi": api/payments-api.md
      - "IPluginsMgrApi": api/plugins-mgr-api.md
      - "IPurchaseRequest": api/purchase-request.md
      - "ISessionsMgrApi": api/sessions-mgr-api.md
      - "IStorageApi": api/storage-api.md
      - "IThemesApi": api/themes-api.md
      - "ITrafficApi": api/network-traffic.md
      - "IUciApi": api/uci-api.md
      - "IUIAPI": api/ui-api.md
      - "IVouchersApi": api/voucher-api.md
      - "IWifiApi": api/wifi-api.md
      - "Plugin Info": api/plugin-info.md
      - "plugin.json": api/plugin.json.md
      - "window.$flare": api/flare-variable.md
  - Free Plugins:
      - "Flarewifi Theme": "plugins/com.flarego.default-theme.md"

copyright: |
  &copy; 2024 <a href="https://www.flarego.ph">Flarego Technologies Corp.</a>

extra:
  generator: false
