//go:build !mono

package boot

import (
	"context"
	"fmt"
	"path/filepath"

	"core/internal/api"
	"core/utils/config"
	"core/utils/env"
	"core/utils/migrate"
	"core/utils/plugins"

	sdkapi "sdk/api"

	sdkutils "github.com/flarehotspot/sdk-utils"
)

func InitPlugins(g *api.CoreGlobals) error {
	db := g.CoreAPI.SqlDB()
	localPlugins := plugins.LocalPluginSrcDefs()
	systemPlugins := plugins.SystemPluginSrcDefs()
	develPlugins := plugins.DevelPluginSrcDefs()

	if env.GO_ENV != env.ENV_PRODUCTION {
		for _, def := range systemPlugins {
			if info, err := sdkutils.GetPluginInfoFromPath(def.LocalPath); err == nil && plugins.IsToBeRemoved(info.Package) {
				continue
			}
			_, err := plugins.InstallSrcDef(db, def, plugins.InstallOpts{ForceInstall: true, Def: def})
			if err != nil {
				return fmt.Errorf("error installing plugin %s: %w", def.LocalPath, err)
			}
		}

		for _, def := range localPlugins {
			if info, err := sdkutils.GetPluginInfoFromPath(def.LocalPath); err == nil && plugins.IsToBeRemoved(info.Package) {
				continue
			}
			_, err := plugins.InstallSrcDef(db, def, plugins.InstallOpts{ForceInstall: true, Def: def})
			if err != nil {
				return fmt.Errorf("error installing plugin %s: %w", def.LocalPath, err)
			}
		}
	}

	for _, def := range develPlugins {
		_, err := plugins.InstallSrcDef(db, def, plugins.InstallOpts{ForceInstall: true, Def: def})
		if err != nil {
			// Devel plugins are development-only; in non-production a failure to
			// install one must abort boot like any other plugin (production keeps
			// the historical best-effort behavior — devel plugins ship there).
			if env.GO_ENV != env.ENV_PRODUCTION {
				return fmt.Errorf("error installing devel plugin %s: %w", def.LocalPath, err)
			}
		}
	}

	// Get current language for translations (only needed if not in dev mode)
	currentLang := "en"
	if env.GO_ENV != env.ENV_DEV {
		cfg, err := config.ReadApplicationConfig()
		if err == nil {
			currentLang = cfg.Lang
		}
	}

	// Process pending removals before loading plugins
	for _, dir := range plugins.InstalledPluginDirs() {
		pkg := filepath.Base(dir)
		if plugins.IsToBeRemoved(pkg) {
			if err := plugins.UninstallPlugin(pkg, db); err != nil {
			}
		}
	}

	// NOTE: staged updates (core + plugins) are applied by the non-mono boot
	// script (start.sh) BEFORE the server starts — it overlays every
	// package staged under data/storage/system/updates/{pkg} onto its install
	// location. By the time we reach here the swap is already done and the new
	// plugin.so is on disk, so there is no Go-side apply step. (A Go plugin.so is
	// ABI-locked to its core build and plugin.Open cannot reload, which is exactly
	// why the swap must happen in the shell before any plugin is loaded.)

	// Register statically-linked system plugins first (generated by
	// core/cmd/sysplugin-prepare into core/internal/api/system-plugins-init.go).
	// These plugins have their Go code compiled into the core binary, so they
	// are NOT loaded via plugin.Open in the loop below — that would try to
	// dlopen a plugin.so file that does not exist for them.
	g.PluginMgr.LoadSystemPlugins(g)

	// Load plugins
	pluginDirs := plugins.InstalledPluginDirs()
	for _, dir := range pluginDirs {
		info, err := sdkutils.GetPluginInfoFromPath(dir)
		if err != nil {

			pkg := filepath.Base(dir)

			// In development every plugin must load successfully: abort boot so
			// the failure is fixed instead of silently shipping a broken plugin
			// set. Production stays resilient (notify + restore from backup +
			// keep booting) so one bad plugin can't brick a device in the field.
			if env.GO_ENV != env.ENV_PRODUCTION {
				return fmt.Errorf("plugin %q failed to load: %w", pkg, err)
			}

			notifyPluginLoadFailure(g, pkg, err)
			if err := LoadFromBackup(g, pkg); err != nil {
				notifyPluginBackupFailure(g, pkg, err)
			}

			continue
		}

		// Run migrations for every installed plugin dir up-front, before the
		// loader-specific paths diverge. This guarantees system plugins (whose
		// Go code is statically linked and registered by LoadSystemPlugins
		// above) still get their schema applied even if the generated loader
		// somehow doesn't run them — e.g. a binary built without the
		// sysplugin-prepare step, where LoadSystemPlugins is the no-op stub
		// and would otherwise leave migrations unrun in production
		// (env.ENV_PRODUCTION skips the dev-only InstallSrcDef block above).
		// MigrateUp is idempotent — it tracks done state per file in a tx —
		// so running it here is safe even when LoadSystemPlugins also ran it.
		// Pass the plugin root dir; MigrateUp resolves resources/migrations
		// itself (same convention as the mono loader and RunCoreMigrations).
		if err := migrate.MigrateUp(db, dir); err != nil {
		}

		// Skip any plugin already registered by LoadSystemPlugins above
		// (statically-linked system plugins compiled into the core binary).
		// Falling through would invoke plugin.Open on a plugin.so that does
		// not exist for them. Using PluginMgr.FindByPkg keeps this in lock-
		// step with whatever LoadSystemPlugins actually registered — no
		// parallel bookkeeping needed.
		if _, alreadyLoaded := g.PluginMgr.FindByPkg(info.Package); alreadyLoaded {
			continue
		}

		// Ensure plugin translations are available for current language (skip in dev mode)
		if env.GO_ENV != env.ENV_DEV {
			if err := sdkutils.EnsureTranslations(dir, currentLang); err != nil {
			}
		}

		p := api.NewPluginApi(dir, info, g.GlobalAssets, g.PluginMgr, g.TrafficMgr, g.WifiMgr)
		err = g.PluginMgr.RegisterPlugin(p)
		if err != nil {
			// Dev: a plugin that fails to compile/load aborts boot (see above).
			// Production: notify the admin and try to recover from backup.
			if env.GO_ENV != env.ENV_PRODUCTION {
				return fmt.Errorf("plugin %q failed to load: %w", info.Package, err)
			}

			notifyPluginLoadFailure(g, info.Package, err)
			if err := LoadFromBackup(g, info.Package); err != nil {
				notifyPluginBackupFailure(g, info.Package, err)
			}
		}
	}

	return nil
}

// notifyPluginLoadFailure records a plugin load/compile failure surfaced at boot
// (e.g. a stale plugin.so that fails plugin.Open with "different version of
// package", or any other dlopen error). The detailed cause is always logged for
// diagnostics; in production it additionally raises an admin notification so the
// operator knows a plugin failed and needs attention. The user-facing message is
// kept generic — it names only the plugin package, never the underlying error or
// .so path — per the error-message hygiene rules; the specifics stay in the log.
func notifyPluginLoadFailure(g *api.CoreGlobals, pkg string, cause error) {
	if err := g.CoreAPI.Logger().Error(fmt.Sprintf("plugin %q failed to load: %v", pkg, cause)); err != nil {
	}

	if env.GO_ENV != env.ENV_PRODUCTION {
		return
	}

	subject := g.CoreAPI.Translate("error", "Plugin failed to load")
	content := fmt.Sprintf("%s: %s", g.CoreAPI.Translate("error", "A plugin failed to load and may be unavailable until you reinstall or update it"), pkg)

	if err := g.CoreAPI.Notification().AddNotification(context.Background(), sdkapi.AddNotificationParams{
		Subject: subject,
		Content: content,
		Type:    sdkapi.NotificationTypeError,
	}); err != nil {
		if logErr := g.CoreAPI.Logger().Error(fmt.Sprintf("failed to notify admin of plugin load failure for %q: %v", pkg, err)); logErr != nil {
		}
	}
}

// notifyPluginBackupFailure records that recovery from backup also failed after a
// plugin failed to load — the plugin could not be restored to a working state and
// is now unavailable. The detailed cause is always logged; in production an admin
// notification is raised so the operator knows manual recovery (reinstall) is
// required. The user-facing message names only the package, never the underlying
// error or filesystem path, per the error-message hygiene rules.
func notifyPluginBackupFailure(g *api.CoreGlobals, pkg string, cause error) {
	if err := g.CoreAPI.Logger().Error(fmt.Sprintf("plugin %q failed to restore from backup: %v", pkg, cause)); err != nil {
	}

	if env.GO_ENV != env.ENV_PRODUCTION {
		return
	}

	subject := g.CoreAPI.Translate("error", "Plugin recovery failed")
	content := fmt.Sprintf("%s: %s", g.CoreAPI.Translate("error", "A plugin failed to load and could not be restored from backup. Please reinstall it"), pkg)

	if err := g.CoreAPI.Notification().AddNotification(context.Background(), sdkapi.AddNotificationParams{
		Subject: subject,
		Content: content,
		Type:    sdkapi.NotificationTypeError,
	}); err != nil {
		if logErr := g.CoreAPI.Logger().Error(fmt.Sprintf("failed to notify admin of plugin backup recovery failure for %q: %v", pkg, err)); logErr != nil {
		}
	}
}

func LoadFromBackup(g *api.CoreGlobals, pkg string) error {
	if err := plugins.RestoreBackup(pkg); err != nil {
		return fmt.Errorf("%w: Error restoring backup for plugin: %s", err, pkg)
	}

	pkgInstallDir := plugins.GetInstallPath(pkg)
	info, err := sdkutils.GetPluginInfoFromPath(pkgInstallDir)
	if err != nil {
		return fmt.Errorf("error getting plugin info: %w", err)
	}

	p := api.NewPluginApi(pkgInstallDir, info, g.GlobalAssets, g.PluginMgr, g.TrafficMgr, g.WifiMgr)
	if err := g.PluginMgr.RegisterPlugin(p); err != nil {
		return err
	}

	plugins.RemoveBackup(pkg)

	return nil
}
