//go:build !mono

package boot

import (
	"fmt"
	"log"
	"path/filepath"

	"core/internal/api"
	"core/utils/config"
	"core/utils/env"
	"core/utils/migrate"
	"core/utils/plugins"

	sdkutils "github.com/flarehotspot/sdk-utils"
)

func InitPlugins(g *api.CoreGlobals) error {
	db := g.CoreAPI.SqlDB()
	localPlugins := plugins.LocalPluginSrcDefs()
	systemPlugins := plugins.SystemPluginSrcDefs()
	develPlugins := plugins.DevelPluginSrcDefs()

	if env.GO_ENV != env.ENV_PRODUCTION {
		for _, def := range systemPlugins {
			if info, err := sdkutils.GetPluginInfoFromPath(def.LocalPath); err == nil && plugins.IsToBeRemoved(info.Package) {
				log.Printf("Skipping force-reinstall of system plugin marked for removal: %s", info.Package)
				continue
			}
			_, err := plugins.InstallSrcDef(db, def, plugins.InstallOpts{ForceInstall: true, Def: def})
			if err != nil {
				return fmt.Errorf("error installing plugin %s: %w", def.LocalPath, err)
			}
		}

		for _, def := range localPlugins {
			if info, err := sdkutils.GetPluginInfoFromPath(def.LocalPath); err == nil && plugins.IsToBeRemoved(info.Package) {
				log.Printf("Skipping force-reinstall of local plugin marked for removal: %s", info.Package)
				continue
			}
			_, err := plugins.InstallSrcDef(db, def, plugins.InstallOpts{ForceInstall: true, Def: def})
			if err != nil {
				return fmt.Errorf("error installing plugin %s: %w", def.LocalPath, err)
			}
		}
	}

	for _, def := range develPlugins {
		_, err := plugins.InstallSrcDef(db, def, plugins.InstallOpts{ForceInstall: true, Def: def})
		if err != nil {
			log.Printf("Warning: error installing devel plugin %s: %v (continuing)", def.LocalPath, err)
		}
	}

	// Get current language for translations (only needed if not in dev mode)
	currentLang := "en"
	if env.GO_ENV != env.ENV_DEV {
		cfg, err := config.ReadApplicationConfig()
		if err == nil {
			currentLang = cfg.Lang
		}
	}

	// Process pending removals before loading plugins
	for _, dir := range plugins.InstalledPluginDirs() {
		pkg := filepath.Base(dir)
		if plugins.IsToBeRemoved(pkg) {
			log.Printf("Removing plugin marked for uninstall: %s", pkg)
			if err := plugins.UninstallPlugin(pkg, db); err != nil {
				log.Printf("Error uninstalling plugin %s: %v", pkg, err)
			}
		}
	}

	// Register statically-linked system plugins first (generated by
	// core/cmd/sysplugin-prepare into core/internal/api/system-plugins-init.go).
	// These plugins have their Go code compiled into the core binary, so they
	// are NOT loaded via plugin.Open in the loop below — that would try to
	// dlopen a plugin.so file that does not exist for them.
	g.PluginMgr.LoadSystemPlugins(g)

	// Load plugins
	pluginDirs := plugins.InstalledPluginDirs()
	for _, dir := range pluginDirs {
		info, err := sdkutils.GetPluginInfoFromPath(dir)
		if err != nil {

			pkg := filepath.Base(dir)
			if err := LoadFromBackup(g, pkg); err != nil {
				g.CoreAPI.Logger().Error(fmt.Sprintf("Error loading from backup: %v", err))
			}

			continue
		}

		// Run migrations for every installed plugin dir up-front, before the
		// loader-specific paths diverge. This guarantees system plugins (whose
		// Go code is statically linked and registered by LoadSystemPlugins
		// above) still get their schema applied even if the generated loader
		// somehow doesn't run them — e.g. a binary built without the
		// sysplugin-prepare step, where LoadSystemPlugins is the no-op stub
		// and would otherwise leave migrations unrun in production
		// (env.ENV_PRODUCTION skips the dev-only InstallSrcDef block above).
		// MigrateUp is idempotent — it tracks done state per file in a tx —
		// so running it here is safe even when LoadSystemPlugins also ran it.
		// Pass the plugin root dir; MigrateUp resolves resources/migrations
		// itself (same convention as the mono loader and RunCoreMigrations).
		if err := migrate.MigrateUp(db, dir); err != nil {
			log.Printf("Error in running migration for plugin %s: %+v\n", dir, err)
		}

		// Skip any plugin already registered by LoadSystemPlugins above
		// (statically-linked system plugins compiled into the core binary).
		// Falling through would invoke plugin.Open on a plugin.so that does
		// not exist for them. Using PluginMgr.FindByPkg keeps this in lock-
		// step with whatever LoadSystemPlugins actually registered — no
		// parallel bookkeeping needed.
		if _, alreadyLoaded := g.PluginMgr.FindByPkg(info.Package); alreadyLoaded {
			log.Printf("Skipping .so registration for already-loaded plugin: %s", info.Package)
			continue
		}

		// Ensure plugin translations are available for current language (skip in dev mode)
		if env.GO_ENV != env.ENV_DEV {
			if err := sdkutils.EnsureTranslations(dir, currentLang); err != nil {
				log.Printf("Warning: Failed to ensure translations for plugin %s: %v", info.Package, err)
			}
		}

		p := api.NewPluginApi(dir, info, g.GlobalAssets, g.PluginMgr, g.TrafficMgr, g.WifiMgr)
		err = g.PluginMgr.RegisterPlugin(p)
		if err != nil {
			if err := LoadFromBackup(g, info.Package); err != nil {
				g.CoreAPI.Logger().Error(fmt.Sprintf("Error loading from backup: %v", err))
			}
		}
	}

	return nil
}

func LoadFromBackup(g *api.CoreGlobals, pkg string) error {
	if err := plugins.RestoreBackup(pkg); err != nil {
		return fmt.Errorf("%w: Error restoring backup for plugin: %s", err, pkg)
	}

	pkgInstallDir := plugins.GetInstallPath(pkg)
	info, err := sdkutils.GetPluginInfoFromPath(pkgInstallDir)
	if err != nil {
		return fmt.Errorf("error getting plugin info: %w", err)
	}

	p := api.NewPluginApi(pkgInstallDir, info, g.GlobalAssets, g.PluginMgr, g.TrafficMgr, g.WifiMgr)
	if err := g.PluginMgr.RegisterPlugin(p); err != nil {
		return err
	}

	plugins.RemoveBackup(pkg)

	return nil
}
